CREATE TABLE [dbo].[ChatMembers]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[ChatId] INT NOT NULL,
	[UserId] nvarchar(450) NOT NULL,
	CONSTRAINT [FK_ChatMembers_ChatId] FOREIGN KEY (ChatId) REFERENCES Chats (Id) ON DELETE CASCADE,
	CONSTRAINT [FK_ChatMembers_UserId] FOREIGN KEY (UserId) REFERENCES AspNetUsers (Id) ON DELETE CASCADE
)
